### ISSUE TITLE
Fix 'Rule is empty.' issue in css\main.css

### ISSUE THREAD

**Issue by ExEr7um** [DreamSites/halat-shop#25]
[CodeFactor](https://www.codefactor.io/repository/github/dreamsites/halat-shop/overview/beta) found an issue: Rule is empty.

It's currently on:
[css\main.css:778
](https://www.codefactor.io/repository/github/dreamsites/halat-shop/source/beta/css/main.css#L778)Commit 4fb455533c3dd9ebdb97542075d2d118106ff6e4

**Comment by ExEr7um** [comment]
Чтобы пофиксить, нужно написать:
``` css
.workBlocks {
  grid-template-columns: auto;
}
```
